spring.application.name=jaf

# Filestack - Credenciais do painel: https://dev.filestack.com
filestack.api-key=AEGlrhBetRoacvdZxvEq3z
filestack.policy=filestack.policy={"expiry":1893456000,"call":["ocr"]}
filestack.signature=a6db5f28919c902dd4e0c9c30e95b28e6ac07d3aa076f6d11c72976a45f31c6d

# Anthropic - Credenciais do painel: https://console.anthropic.com
anthropic.api-key=SUA_API_KEY_ANTHROPIC
