package com.jaf.application.enums;

public enum Permissao {
    // OBRAS
    CRIAR_OBRA,
    EDITAR_OBRA,
    DELETAR_OBRA,
    VISUALIZAR_OBRA,

    // FUNCIONARIOS
    CRIAR_FUNCIONARIO,
    EDITAR_FUNCIONARIO,
    DELETAR_FUNCIONARIO,
    VISUALIZAR_FUNCIONARIOS,

    // GASTOS
    CRIAR_GASTO,
    EDITAR_GASTO,
    DELETAR_GASTO,
    VISUALIZAR_GASTOS,

    // ALOCACOES
    CRIAR_ALOCACAO,
    EDITAR_ALOCACAO,
    DELETAR_ALOCACAO,
    VISUALIZAR_ALOCACOES,

    // RELATORIOS
    GERAR_RELATORIO,
    VISUALIZAR_RELATORIO,

    // PRESENCAS
    REGISTRAR_PRESENCA,
    EDITAR_PRESENCA,
    DELETAR_PRESENCA,
    VISUALIZAR_PRESENCAS
}
